language: node_js
node_js:
  - node
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn@latest
  - yarn --version
install:
  - yarn
script:
  - yarn run lint
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000 & yarn run test
