language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn@latest
  - yarn --version
install:
  - yarn
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -L https://raw.githubusercontent.com/GoogleChrome/lighthouse/v2.1.0/lighthouse-core/scripts/download-chrome.sh | bash
script:
  - yarn run lint
  - yarn run test
