language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn@latest
  - yarn --version
install:
  - yarn
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - yarn run lint
  - yarn run test
